apiVersion: v1
kind: ServiceAccount
metadata:
  name: streamlit
  namespace: semantic-pokedex
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/semantic-pokedex-streamlit-irsa
