Resources:
  SemanticPokedexDbSecretReference:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: ${env:DB_SECRET_ARN}
      TargetId: semantic-pokedex-db-placeholder-target
      TargetType: AWS::RDS::DBInstance
